services:
  agent-prime:
    build: ./agent-prime
    container_name: agent-prime
    restart: always
    environment:
      - PORT=8001
    volumes:
      - ./.env:/app/.env
      - ~/.config/gcloud:/home/myuser/.config/gcloud
    ports:
      - 0.0.0.0:8001:8001
    develop:
      watch:
        - action: sync+restart
          path: agent-prime/agent_prime
          target: /app

  agent-host:
    build: ./agent-host
    container_name: agent-host
    restart: always
    env_file: ".env"
    environment:
      - PORT=8000
    volumes:
      - ./.env:/app/.env
      - ./agent_registry.csv:/app/agent_host/registry/agent_registry.csv
      - ~/.config/gcloud:/home/myuser/.config/gcloud
    ports:
      - 0.0.0.0:8000:8000
    develop:
      watch:
        - action: sync+restart
          path: agent-host/agent_host
          target: /app


networks:
  default:
    name: agent_default
